# Generated by Django 3.1.5 on 2021-07-14 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_install_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='is_editing_active',
            field=models.BooleanField(default=False, help_text='If an editor is writing feedback then True otherwise False'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('created_on', models.DateTimeField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.essay')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='feedback',
            field=models.ForeignKey(blank=True, help_text='The feedback given to an essay by an editor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='project.feedback'),
        ),
    ]
